services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5137:80"
    environment:
      - VITE_OPENWEATHER_API_KEY=${VITE_OPENWEATHER_API_KEY}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://weather.emmi.zone/api}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge

